### ISSUE TITLE
Improve the syntax and make it feel more native

### ISSUE THREAD

**Issue by sairam4123** [niklas2902/py4godot#48]
Hello, I'm Sairam, I really appreciate your work and time you put into this. But I think that this project can be made to feel more Pythonic by incorporating following changes.

# Using api similar to DataClasses
You can use an api similar to Pydantic for properties which allows us to really improve the feel of the code.
Here's an Example of what I mean:
```py
from godot.classes import gdclass
from godot.types.variant import Vector2

@gdclass
class Player(Node3D):
    speed: Vector2
    direction: Vector2 = Vector2.ZERO  # (you can use class attributes to behave like native GDScript)
    
    def __init__(self):
        # handle initialization, it is similar to _init
        pass
    
    def __ready__(self):
        # handle ready event etc.
        pass
        
    
    # by default all methods are public
    def move(self):
        pass

    @private
    def _animate():
       pass
      
 ```
 
 # Signals can be implemented like this.
 I really appreciate any input on this syntax as well.
 
 ```py
from godot.class import gdclass
from godot.signals import gdsignal

@gdclass
class Player(Node2D):
    
    signal_name = gdsignal({"input": int})
    
    direction: Vector2 = Vector2.ONE
    

 ```

**Comment by niklas2902** [comment]
Thank you very much for your feedback. This helps a lot. I will look into it, but it could take a bit of time
