### ISSUE TITLE
Error generating generate_*.py in a non-UTF-8 operating system

### ISSUE THREAD

**Issue by zack-luan** [niklas2902/py4godot#49]
For example, in line 1918 of generate_classes_cpp.py, the following code:
with open('py4godot/gdextension-api/extension_api.json', 'r', encoding='utf-8') as myfile:
The absence of the encoding='utf-8' parameter causes an error when data = myfile.read() is executed, and it is hoped that this can be improved.

**Comment by niklas2902** [comment]
I'm very sorry. I hope, I fixed it now
